# Generated by Django 3.2.7 on 2021-09-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='regions',
        ),
        migrations.AddField(
            model_name='organization',
            name='regions',
            field=models.ManyToManyField(related_name='ads_by_region', to='ads.Region'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='organizsation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_ads', to='ads.organization'),
        ),
    ]
