# Generated by Django 3.2.7 on 2021-09-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20210916_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Беларусь', max_length=255),
        ),
        migrations.CreateModel(
            name='OrganisationContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adres', models.CharField(max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.organization')),
            ],
        ),
    ]
